baseURL: "https://cemeroncel.github.io/" 
title: Cem Eröncel
pagination:
    pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: Projects
          url: /projects/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 4     

params:
    description: "I am an assistant professor at the Electric-Electronics Engineering department of Istinye University. My interests are theoretical and computational cosmology, in particular the nature of dark matter and its impact on structure formation."
    author: Cem Eröncel
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Cem Eröncel
          subtitle: "I am an assistant professor at the Electric-Electronics Engineering department of Istinye University. My interests are theoretical and computational cosmology, in particular the nature of dark matter and its impact on structure formation."
          imageUrl: "/me.jpg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Cem Eröncel
          buttons:
            - name: Papers
              url: /papers/
            - name: Courses
              url: /courses/
            - name: Projects
              url: /projects/
            - name: CV
              url: "/cv.pdf"
    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: "mailto:cem.eroncel@istinye.edu.tr"
#        - name: Location
#          url: /location/
#        - name: Office Hours
#          url: /officehours/
        - name: Inspire
          url: "https://inspirehep.net/authors/1705253?ui-citation-summary=true"
#        - name: YouTube
#          url: "https://www.youtube.com/@pmichaillat"
        - name: GitHub
          url: "https://github.com/cemeroncel"
#        - name: Substack
#          url: "https://pmichaillat.substack.com"
        - name: Orcid
          url: "https://orcid.org/my-orcid?orcid=0000-0002-9308-1449"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Cem Eröncel"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
